metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "6fd57719f75440ddfc49540fe4d865b14cde9a341bba1f2a50109535e51d97ce"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "Q7BS4Wgn1B3b4whB6Y9cbUc1nSiue2nggy67SNDsxm0="
metrics_token = "mOSX9FsWzFuKYmUfqeNzh6g2EFAWl/gH2iBXpt7ypCU="
